# Generated by Django 4.2 on 2025-06-02 23:08

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('patronymic', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-ZА-Яа-яЁё]+$', 'Разрешены только буквы.')], verbose_name='Отчество')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
                ('is_archived', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('full_text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Полный текст')),
                ('category', models.CharField(choices=[('Акции и Скидки', 'Акции и Скидки'), ('Новости клиники', 'Новости клиники'), ('Услуги и процедуры', 'Услуги и процедуры'), ('Полезные советы', 'Полезные советы'), ('Вопрос-ответ', 'Вопрос-ответ')], max_length=50, verbose_name='Категория')),
                ('img', models.ImageField(upload_to='articles/', verbose_name='Картинка статьи')),
                ('publication_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-ZА-Яа-яЁё]+$', 'Разрешены только буквы.')], verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-ZА-Яа-яЁё]+$', 'Разрешены только буквы.')], verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-ZА-Яа-яЁё]+$', 'Разрешены только буквы.')], verbose_name='Отчество')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='Фото врача')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Почта')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='Стаж работы (лет)')),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200, verbose_name='Учебное заведение')),
                ('degree', models.CharField(max_length=200, verbose_name='Степень/Специальность')),
                ('year_of_graduation', models.IntegerField(verbose_name='Год окончания')),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
            },
        ),
        migrations.CreateModel(
            name='ServiceСategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='service_categories/', verbose_name='Фото категории')),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Категория услуги',
                'verbose_name_plural': 'Категории услуг',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='service/', verbose_name='Фото услуги')),
                ('is_archived', models.BooleanField(default=False)),
                ('doctors', models.ManyToManyField(related_name='services', to='stomatology_app.doctors', verbose_name='Врачи')),
                ('service_categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stomatology_app.serviceсategories', verbose_name='Категория услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='FreeTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.CharField(choices=[('09:00-09:30', '09:00-09:30'), ('09:30-10:00', '09:30-10:00'), ('10:00-10:30', '10:00-10:30'), ('10:30-11:00', '10:30-11:00'), ('11:00-11:30', '11:00-11:30'), ('11:30-12:00', '11:30-12:00'), ('12:00-12:30', '12:00-12:30'), ('12:30-13:00', '12:30-13:00'), ('13:00-13:30', '13:00-13:30'), ('13:30-14:00', '13:30-14:00'), ('14:00-14:30', '14:00-14:30'), ('14:30-15:00', '14:30-15:00'), ('15:00-15:30', '15:00-15:30'), ('15:30-16:00', '15:30-16:00'), ('16:00-16:30', '16:00-16:30'), ('16:30-17:00', '16:30-17:00'), ('17:00-17:30', '17:00-17:30'), ('17:30-18:00', '17:30-18:00'), ('18:00-18:30', '18:00-18:30'), ('18:30-19:00', '18:30-19:00'), ('19:00-19:30', '19:00-19:30'), ('19:30-20:00', '19:30-20:00'), ('20:00-20:30', '20:00-20:30'), ('20:30-21:00', '20:30-21:00')], max_length=20, verbose_name='Время')),
                ('is_archived', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stomatology_app.doctors', verbose_name='Врач')),
            ],
            options={
                'verbose_name': 'Доступное время приема',
                'verbose_name_plural': 'Доступное время приемов',
            },
        ),
        migrations.AddField(
            model_name='doctors',
            name='education',
            field=models.ManyToManyField(blank=True, to='stomatology_app.education', verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='specializations',
            field=models.ManyToManyField(blank=True, to='stomatology_app.specialization', verbose_name='Специализации'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт'),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_service', models.CharField(blank=True, max_length=255, null=True, verbose_name='Другая услуга')),
                ('is_archived', models.BooleanField(default=False)),
                ('appointment', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='doctor', chained_model_field='doctor', on_delete=django.db.models.deletion.CASCADE, to='stomatology_app.freetime', verbose_name='Запись на прием')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stomatology_app.doctors', verbose_name='Врач')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stomatology_app.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Консультация',
                'verbose_name_plural': 'Консультации',
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('no_answer', 'Нет ответа'), ('failed', 'Не удалось')], max_length=50, verbose_name='Статус звонка')),
                ('called_at', models.DateTimeField(auto_now_add=True, verbose_name='Время звонка')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивировано')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='stomatology_app.consultation', verbose_name='Консультация')),
            ],
            options={
                'verbose_name': 'Журнал коммуникаций',
                'verbose_name_plural': 'Журналы коммуникаций',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stomatology_app.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stomatology_app.patient', verbose_name='Пациент'),
        ),
    ]
